// <auto-generated />
using System;
using BookStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookStore.Infrastructure.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("CodAs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodAs"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CodAs");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("CodAu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodAu"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CodAu");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("CodL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodL"));

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("Edicao")
                        .HasColumnType("integer");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CodL");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroAssunto", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("integer");

                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("integer");

                    b.HasKey("Livro_CodL", "Assunto_CodAs");

                    b.HasIndex("Assunto_CodAs");

                    b.ToTable("LivroAssuntos");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroAutor", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("integer");

                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("integer");

                    b.HasKey("Livro_CodL", "Autor_CodAu");

                    b.HasIndex("Autor_CodAu");

                    b.ToTable("LivroAutores");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroValor", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVenda_CodTv")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Livro_CodL", "TipoVenda_CodTv");

                    b.HasIndex("TipoVenda_CodTv");

                    b.ToTable("LivroValores");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.TipoVenda", b =>
                {
                    b.Property<int>("CodTv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodTv"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CodTv");

                    b.ToTable("TiposVenda");

                    b.HasData(
                        new
                        {
                            CodTv = 1,
                            Descricao = "Balcão"
                        },
                        new
                        {
                            CodTv = 2,
                            Descricao = "Self-Service"
                        },
                        new
                        {
                            CodTv = 3,
                            Descricao = "Internet"
                        },
                        new
                        {
                            CodTv = 4,
                            Descricao = "Evento"
                        });
                });

            modelBuilder.Entity("BookStore.Domain.Entities.VwRelatorioLivrosPorAutor", b =>
                {
                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edicao")
                        .HasColumnType("integer");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorBalcao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorEvento")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorInternet")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorSelfService")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("VwRelatorioLivrosPorAutor", (string)null);
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroAssunto", b =>
                {
                    b.HasOne("BookStore.Domain.Entities.Assunto", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroAutor", b =>
                {
                    b.HasOne("BookStore.Domain.Entities.Autor", "Autor")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.LivroValor", b =>
                {
                    b.HasOne("BookStore.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroValores")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Domain.Entities.TipoVenda", "TipoVenda")
                        .WithMany("LivroValores")
                        .HasForeignKey("TipoVenda_CodTv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("TipoVenda");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("LivroAssuntos");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.Autor", b =>
                {
                    b.Navigation("LivroAutores");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.Livro", b =>
                {
                    b.Navigation("LivroAssuntos");

                    b.Navigation("LivroAutores");

                    b.Navigation("LivroValores");
                });

            modelBuilder.Entity("BookStore.Domain.Entities.TipoVenda", b =>
                {
                    b.Navigation("LivroValores");
                });
#pragma warning restore 612, 618
        }
    }
}
